<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<Target Name="CustomCopyDll" AfterTargets="Build">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="C:\zz_trash\cassandra_testing\cassandra\domain_model\" SkipUnchangedFiles="true" />
		<!--<Copy SourceFiles="$(TargetPath)" DestinationFolder="C:\zz_trash\cass_new\cassandra\domain_model\" SkipUnchangedFiles="true" />-->
	</Target>

	<ItemGroup>
	  <Compile Remove="Objects\CandidateSelectorV0.cs" />
	  <Compile Remove="Objects\SCurveDistress - Copy.cs" />
	  <Compile Remove="Objects\StrategyGenerator.cs" />
	  <Compile Remove="Objects\TreatmentsTriggerMCDA - Copy.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="JCass_Core">
	    <HintPath>framework_dlls\JCass_Core.dll</HintPath>
	  </Reference>
	  <Reference Include="JCass_Data">
	    <HintPath>framework_dlls\JCass_Data.dll</HintPath>
	  </Reference>
	  <Reference Include="JCass_ModelCore">
	    <HintPath>framework_dlls\JCass_ModelCore.dll</HintPath>
	  </Reference>
	</ItemGroup>


</Project>
